### ISSUE TITLE
Still won't run

### ISSUE THREAD

**Issue by Wayne-lightform** [LightForm-group/UoM-CSF-matflow#11]
**Describe the problem**
Hi all. I have used the command _module purge; module load apps/anaconda3/5.2.0/bin tools/env/proxy2; /opt/gridware/depots/8e896c5a/el7/pkg/apps/anaconda3/5.2.0/bin/bin/pip install --user -U h5py==2.10.0_. This has made a difference but now I am getting the following error:-
![image](https://user-images.githubusercontent.com/59013576/106940685-c1e84480-6719-11eb-989d-fd3bfe83d8d5.png)

**Expected behavior**
The workflow should take EBSD data in the form of .crc files and run simulations of tensile tests in 3 directions 0, 45 and 90 degrees to the rolling direction of a titanium sheet. I should obtain data to produce stress strain curves.

**Output from `matflow validate`**
![image](https://user-images.githubusercontent.com/59013576/106940818-eba16b80-6719-11eb-97ee-53b8ddb1d38f.png)

**Workflow directory and/or profile location**
The YAML file is located /mnt/eps01-rds/Fonseca-Lightform/shared/matflow-debugging/wayne_uniaxial_multi_directions_2021-02-01-215813

**Comment by aplowman** [comment]
Hi Wayne. You'll need to change the path to the CRC file to wherever you have it (and where it is accessible). Currently, you are trying to access it from my home space, hence the PermissionError.

**Comment by Wayne-lightform** [comment]
Ahh. Didn't notice the paths were different. Thanks Adam. This is now running.
