### ISSUE TITLE
YAML workflow won't run

### ISSUE THREAD

**Issue by Wayne-lightform** [LightForm-group/UoM-CSF-matflow#8]
**Describe the problem**

Hi all. I have a workflow that simply won't run. I have installed U h5py==2.10.0 but it still crashes ,Can anyone see what the issue is?

**Expected behaviour**

The workflow should take EBSD data in the form of .crc files and run simulations of tensile tests in 3 directions 0, 45 and 90 degrees to the rolling direction of a titanium sheet. I should obtain data to produce stress strain curves. 

**Output from Matflow Validate**

![image](https://user-images.githubusercontent.com/59013576/106866112-f92c0680-66c3-11eb-853a-37e09ec9df1c.png)
![image](https://user-images.githubusercontent.com/59013576/106866202-1660d500-66c4-11eb-8527-932cce3c58ff.png)

**Workflow directory and/or profile location**

The YAML file is located /mnt/eps01-rds/Fonseca-Lightform/shared/matflow-debugging/wayne_uniaxial_multi_directions_2021-02-01-215813

**Comment by aplowman** [comment]
Thanks for the issue Wayne. Please could you fill in the other sections of the issue template as well?

**Comment by aplowman** [comment]
Hi Wayne. I believe this issue is resolved now. If so, please could you close it?
